version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html/controle_estoque
    volumes:
      - ./controle_estoque:/var/www/html/controle_estoque
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    ports:
      - "8086:80"
    volumes:
      - ./controle_estoque:/var/www/html/controle_estoque
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: laravel-db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel-network

  node:
    build:
      context: ./controle_estoque
      dockerfile: ../docker/node/Dockerfile
    container_name: laravel-node
    volumes:
      - ./controle_estoque:/app:rw
      - /app/node_modules
    ports:
      - "5173:5173"  # Expõe a porta 5173 do contêiner para a mesma porta na máquina host
    command: npm run dev
    networks:
      - laravel-network
    depends_on:
      - app

volumes:
  db_data:

networks:
  laravel-network: